### ISSUE TITLE
Doesn't seem to run on 10.11.1 (15B42) from Xcode Version 7.1 (7B91b)

### ISSUE THREAD

**Issue by jessegrosjean** [FlexMonkey/OSXMetalParticles#1]
I downloaded latest from git and tried to run the OS X version of the project. There was one syntax error to which Xcode suggested an autocorrection. But once I did that I got an error on the line `commandEncoder.dispatchThreadgroups(threadgroupsPerGrid, threadsPerThreadgroup: threadsPerThreadgroup)`.

Anyway I'm just messing around, but would be great to see this working.

**Comment by FlexMonkey** [comment]
Hi, Metal in 10.11.1 is a little dodgy (luckily it's fixed in 10.11.2). To get this working, edit the scheme and set "Metal API validation" to disabled. Screen clearing isn't working under 10.11.1, but it is in 10.11.2 :)

**Comment by jessegrosjean** [comment]
That solved it, thanks.

**Comment by FlexMonkey** [comment]
I'm going to deprecate this project when I get a chance and add an OS X target to my "proper" particle project: https://github.com/FlexMonkey/ParticleLab

Cheers!
