### ISSUE TITLE
newBufferWithBytesNoCopy :  fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by sushihangover** [FlexMonkey/OSXMetalParticles#2]
OS-X 10.11.2 / Xcode Version 7.2 (7C68) 
Compiling/Run: OSXMetalParticles
- ParticleLab.swift Line 104:

```
particlesBufferNoCopy = device!.newBufferWithBytesNoCopy(particlesMemory, length: Int(particlesMemoryByteSize), options: MTLResourceOptions.CPUCacheModeDefaultCache, deallocator: nil)
```

```
fatal error: unexpectedly found nil while unwrapping an Optional value
```

![screen shot 2016-01-02 at 6 56 55 pm](https://cloud.githubusercontent.com/assets/1294194/12077073/cdc7f14e-b182-11e5-9d58-05c02bcb3cec.png)

I'm lost, I just do not see the error... 

https://developer.apple.com/library/mac/documentation/Metal/Reference/MTLDevice_Ref/index.html#//apple_ref/swift/intfm/MTLDevice/c:objc(pl)MTLDevice(im)newBufferWithBytesNoCopy:length:options:deallocator:

**Comment by FlexMonkey** [comment]
Hi,

I can't replicate that issue on iOS or OS X. It looks like the `device` is nil in your case, but I set that a few lines above:

```
super.init(frame: CGRect(x: 0, y: 0, width: Int(width), height: Int(height)), device:  MTLCreateSystemDefaultDevice())
```

Is it iOS that you are targeting? What device? If it's an older device, it may not support Metal.

**Comment by sushihangover** [comment]
Targeting OS-X...

Ahh... I swapped MacBookPros as I was cloning a drive and this MacBookPro does not support Metal (?). Now I'm confused on which Macs have Metal support or not as I can not find an official Apple requirement/list.

Thanks for the reply... maybe I'll have to go back to OGL till I can drop 2+(?) year old Macs (large part of the market...)

```
Failed to create pipeline state, error (null)
```
